---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resourcequota
  namespace: dev-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1500Mi"
    limits.cpu: "1750"
    limits.memory: "1750Mi"
