---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limitranage
  namespace: dev-ns
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "150m"
        memory: "150Mi"
      default:
        cpu: "300m"
        memory: "300Mi"
      min:
        cpu: "150m"
        memory: "150Mi"
      max:
        cpu: "300m"
        memory: "300Mi"
    
