---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-client-deploy
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      client: tcs
  template:
    metadata:
      name: dev-client-deploy-pod
      labels:
        client: tcs
    spec:
      containers:
        - name: dev-client-deploy-app-cont
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "450Mi"
