---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limitranage
  namespace: dev-ns
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      default:
        cpu: "500m"
        memory: "750Mii"
      min:
        cpu: "250m"
        memory: "512Mi"
      max:
        cpu: "500m"
        memory: "750Mi"
    
