---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resourcequota
  namespace: dev-ns
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
