---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resourcequota
  namespace: dev-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "750Mi"
    limits.cpu: "1500m"
    limits.memory: "1500Gi"
